# Generated by Django 3.2.7 on 2021-09-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stack", models.JSONField(blank=True, null=True)),
                ("dealt_cards", models.JSONField(blank=True, null=True)),
                ("deck_count", models.IntegerField(default=52)),
                ("win_count", models.IntegerField(default=0)),
                ("lose_count", models.IntegerField(default=0)),
                ("total_rounds_count", models.IntegerField(default=0)),
            ],
        ),
    ]
